//
// Created by Atrin Hojjat on 7/13/16.
//

#ifndef PSEUDOIN_RULE_HEBBIAN_SUPERVISED_LEARNING_PERFORMANCENEURALNETWORK_H
#define PSEUDOIN_RULE_HEBBIAN_SUPERVISED_LEARNING_PERFORMANCENEURALNETWORK_H


class PerformanceNeuralNetwork {

};


#endif //PSEUDOIN_RULE_HEBBIAN_SUPERVISED_LEARNING_PERFORMANCENEURALNETWORK_H
