//
// Created by Atrin Hojjat on 7/10/16.
//

#ifndef PSEUDOIN_RULE_HEBBIAN_SUPERVISED_LEARNING_CONJUGATEGRADIENTLEARN_H
#define PSEUDOIN_RULE_HEBBIAN_SUPERVISED_LEARNING_CONJUGATEGRADIENTLEARN_H


class ConjugateGradientLearn {

};


#endif //PSEUDOIN_RULE_HEBBIAN_SUPERVISED_LEARNING_CONJUGATEGRADIENTLEARN_H
